# Generated by Django 5.1.15 on 2026-09-23 04:05

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FotoGaleria',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=150, verbose_name='Título da Foto / Ação')),
                ('imagem', models.ImageField(help_text='Formatos recomendados: JPG, PNG ou WEBP.', upload_to='galeria/%Y/%m/', verbose_name='Arquivo de Imagem')),
                ('descricao', models.TextField(blank=True, help_text='Breve relato sobre a ação realizada ou os pacientes acolhidos.', verbose_name='Descrição ou Legenda')),
                ('data_evento', models.DateField(default=django.utils.timezone.now, verbose_name='Data do Evento')),
                ('link_instagram', models.URLField(blank=True, help_text='Caso a foto tenha uma publicação no @aapocmt correspondente.', verbose_name='Link do Post no Instagram (Opcional)')),
                ('ativo', models.BooleanField(default=True, help_text='Desmarque para ocultar a foto do site sem precisar excluí-la.', verbose_name='Exibir no Site')),
                ('ordem', models.PositiveIntegerField(default=0, help_text='Números menores aparecem primeiro (0 tem prioridade máxima).', verbose_name='Ordem de Prioridade')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Data de Envio')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
            ],
            options={
                'verbose_name': 'Foto da Galeria',
                'verbose_name_plural': 'Galeria de Fotos',
                'ordering': ['ordem', '-data_evento', '-criado_em'],
            },
        ),
    ]
