# Generated by Django 5.1.15 on 2026-09-23 04:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fotogaleria',
            name='data_evento',
            field=models.DateField(default=django.utils.timezone.localdate, verbose_name='Data do Evento'),
        ),
    ]
