# Generated by Django 5.1.15 on 2026-09-23 03:37

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Voluntario',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome_completo', models.CharField(max_length=150, verbose_name='Nome Completo')),
                ('data_nascimento', models.DateField(verbose_name='Data de Nascimento')),
                ('telefone', models.CharField(max_length=20, verbose_name='Telefone / WhatsApp')),
                ('instagram', models.CharField(blank=True, max_length=60, verbose_name='Instagram')),
                ('endereco', models.CharField(max_length=255, verbose_name='Endereço')),
                ('como_deseja_ajudar', models.TextField(verbose_name='Como Deseja Ajudar')),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('EM_CONTATO', 'Em Contato'), ('APROVADO', 'Aprovado'), ('RECUSADO', 'Recusado')], default='PENDENTE', max_length=20, verbose_name='Status da Inscrição')),
                ('observacoes_internas', models.TextField(blank=True, help_text='Anotações da equipe sobre entrevistas, disponibilidade ou histórico.', verbose_name='Observações Internas (Uso Exclusivo da AAPOC)')),
                ('termo_lgpd_aceito', models.BooleanField(default=True, help_text='Indica que o voluntário autorizou o armazenamento de seus dados para contato da AAPOC.', verbose_name='Aceite do Termo de Privacidade (LGPD)')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Data de Inscrição')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
            ],
            options={
                'verbose_name': 'Voluntário',
                'verbose_name_plural': 'Voluntários',
                'ordering': ['-criado_em'],
            },
        ),
    ]
